name: the-world-wp
recipe: pantheon
config:
  framework: wordpress
  id: fa3253e3-f798-4bae-a25f-e278d44a9aab
  site: the-world-wp
  php: "7.4"
  via: apache:2.4
  database: mysql
  ssl: true
services:
  node:
    type: node:16
    build:
      - npm install
      - chmod +x scripts/*
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
tooling:
  wp:
    service: appserver
    cmd: wp --path=/app --url=the-world-wp.lndo.site
  # Lando will run sh scripts but does not recognize the lando command within.
  # local:
  #   service: appserver
  #   description: Find and replace the domain for local environment, and import configuration
  #   cmd:
  #     - './scripts/refresh.sh'
  # refresh:
  #   service: appserver
  #   description: Import database, find and replace the domain for local environment, and import configuration
  #   cmd:
  #     - './scripts/refresh.sh'
  npm:
    service: node
  node:
    service: node
events:
  post-db-import:
    - appserver:
      # Replace Wordpress domain in the database pantheon dev environment
      - wp --path=/app --url=dev-the-world-wp.pantheonsite.io search-replace 'dev-the-world-wp.pantheonsite.io' 'the-world-wp.lndo.site'
