<?php
/**
 * Define global plugins.
 *
 * @package the_world_site_config
 */

define(
	'GLOBAL_PLUGINS',
	array(
		'wp-native-php-sessions/pantheon-sessions.php',
		'admin-taxonomy-filter/admin-taxonomy-filter.php',
		'advanced-custom-fields-pro/acf.php',
		'acf-to-rest-api/class-acf-to-rest-api.php',
		'PATCH-s3-uploads/s3-uploads.php',
		'codepress-admin-columns/codepress-admin-columns.php',
		'custom-post-type-ui/custom-post-type-ui.php',
		'disable-comments/disable-comments.php',
		'genesis-custom-blocks/genesis-custom-blocks.php',
		'PATCH-external-media-without-import/external-media-without-import.php',
		'newspack-blocks/newspack-blocks.php',
		'newspack-image-credits/newspack-image-credits.php',
		'newspack-newsletters/newspack-newsletters.php',
		'pwa/pwa.php',
		'redirection/redirection.php',
		'user-role-editor/user-role-editor.php',
		'tw-contributors/tw-contributors.php',
		'tw-custom-tags/tw-custom-tags.php',
		'tw-episodes/tw-episodes.php',
		'tw-media/tw-media.php',
		'tw-endpoint-helper/tw-endpoint-helper.php',
		'tw-programs/tw-programs.php',
		'tw-qa-block/tw-qa-block.php',
		'tw-resource-development-tags/tw-resource-development-tags.php',
		'tw-segments/tw-segments.php',
		'tw-story-types/tw-story-types.php',
		'wordpress-importer/wordpress-importer.php',
		'wordpress-seo/wp-seo.php',
		'wp-cfm-path/wp-cfm-path.php',
		'wp-cfm/wp-cfm.php',
		'xml-sitemap-feed/xml-sitemap.php',
	)
);
