<?php
/**
 * Define global plugins.
 */
define('GLOBAL_PLUGINS', array(
  'wp-native-php-sessions/pantheon-sessions.php',
  'advanced-custom-fields-pro/acf.php',
  'PATCH-s3-uploads/s3-uploads.php',
  'custom-post-type-ui/custom-post-type-ui.php',
  'custom-simple-rss/custom-simple-rss.php',
  'disable-comments/disable-comments.php',
  'PATCH-external-media-without-import/external-media-without-import.php',
  'newspack-blocks/newspack-blocks.php',
  'newspack-image-credits/newspack-image-credits.php',
  'newspack-newsletters/newspack-newsletters.php',
  'pwa/pwa.php',
  'redirection/redirection.php',
  'user-role-editor/user-role-editor.php',
  'tw-contributors/tw-contributors.php',
  'tw-episodes/tw-episodes.php',
  'tw-programs/tw-programs.php',
  'tw-resource-development-tags/tw-resource-development-tags.php',
  'tw-story-types/tw-story-types.php',
  'wordpress-importer/wordpress-importer.php',
  'wordpress-seo/wp-seo.php',
  'wp-cfm-path/wp-cfm-path.php',
  'wp-cfm/wp-cfm.php',
  'xml-sitemap-feed/xml-sitemap.php',
));
